### ISSUE TITLE
Segmentation fault on typo in fx2pipe

### ISSUE THREAD

**Issue by nebanks** [hoglet67/6502Decoder#9]
I added an extra 'i' to the -ifclk parameter. fx2pipe does not react gracefully:
:)
`paganini@Ariel:~$ sudo fx2pipe -ifclik=xi -n=4k >16.bin`
`Segmentation fault`

`paganini@Ariel:~$ uname -a
Linux Ariel 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linu`

**Comment by hoglet67** [comment]
Thanks for reporting this.

It should now be fixed in master.

**Comment by nebanks** [comment]
> Thanks for reporting this.
> 
> It should now be fixed in master.

You bet! Thanks for sharing your hard work!
